[CmdletBinding()]param([string]$SqlitePath)
$ErrorActionPreference='Stop';$root=Split-Path -Parent $PSScriptRoot;if($SqlitePath){$env:WAA_SQLITE_TEST=$SqlitePath}
Import-Module (Join-Path $root 'src/Waa.psm1') -Force;. (Join-Path $root 'src/ReportParsing.ps1');. (Join-Path $root 'src/ReportIntake.ps1')
$script:Passed=0
function Assert($Condition,[string]$Message){if(!$Condition){throw "ASSERTION FAILED: $Message"};$script:Passed++;Write-Host "PASS $Message" -ForegroundColor Green}
function Get-Col([int]$Index){$n=$Index+1;$s='';while($n-gt0){$n--; $s=[char](65+($n%26))+$s;$n=[math]::Floor($n/26)};return $s}
function Xml-Escape([string]$s){return [Security.SecurityElement]::Escape($s)}
function New-TestXlsx([string]$Path,[object[]]$Headers,[object[]]$Values){
  Add-Type -AssemblyName System.IO.Compression.FileSystem
  $fs=[IO.File]::Open($Path,[IO.FileMode]::Create);$zip=[IO.Compression.ZipArchive]::new($fs,[IO.Compression.ZipArchiveMode]::Create,$false)
  try{
    function Add-ZipText($z,[string]$name,[string]$text){$e=$z.CreateEntry($name);$sw=[IO.StreamWriter]::new($e.Open(),[Text.Encoding]::UTF8);try{$sw.Write($text)}finally{$sw.Dispose()}}
    $cells1='';for($i=0;$i-lt$Headers.Count;$i++){$r=(Get-Col $i)+'1';$cells1+="<c r=`"$r`" t=`"inlineStr`"><is><t>$(Xml-Escape ([string]$Headers[$i]))</t></is></c>"}
    $cells2='';for($i=0;$i-lt$Values.Count;$i++){$r=(Get-Col $i)+'2';$cells2+="<c r=`"$r`" t=`"inlineStr`"><is><t>$(Xml-Escape ([string]$Values[$i]))</t></is></c>"}
    Add-ZipText $zip 'xl/workbook.xml' '<?xml version="1.0" encoding="UTF-8"?><workbook xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships"><sheets><sheet name="Report" sheetId="1" r:id="rId1"/></sheets></workbook>'
    Add-ZipText $zip 'xl/_rels/workbook.xml.rels' '<?xml version="1.0" encoding="UTF-8"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/worksheet" Target="worksheets/sheet1.xml"/></Relationships>'
    Add-ZipText $zip 'xl/worksheets/sheet1.xml' ("<?xml version=`"1.0`" encoding=`"UTF-8`"?><worksheet xmlns=`"http://schemas.openxmlformats.org/spreadsheetml/2006/main`"><sheetData><row r=`"1`">$cells1</row><row r=`"2`">$cells2</row></sheetData></worksheet>")
  }finally{$zip.Dispose();$fs.Dispose()}
}
$data=Join-Path ([IO.Path]::GetTempPath()) ("waa-tests-"+[guid]::NewGuid());[IO.Directory]::CreateDirectory($data)|Out-Null
try{
  $init=Initialize-Waa $root $data;Initialize-WaaReportIntake $data;Assert ($init.integrity-eq'ok') 'database creation, migration, and integrity';Assert ((Invoke-Sql "PRAGMA journal_mode;").Trim()-eq'wal') 'WAL enabled';Assert ((Invoke-Sql "PRAGMA foreign_keys;").Trim()-eq'1') 'foreign keys enabled on every database connection'
  $jsonRows=@(Invoke-Sql "SELECT 10.0 p UNION ALL SELECT 20.0 p;" -Json);Assert ($jsonRows.Count-eq2-and-($jsonRows[0]-isnot[System.Array])-and[double]$jsonRows[1].p-eq20) 'SQLite JSON rows flatten across PowerShell versions'
  $examples=@{'Orlando Carmona'='CARMONAO';'Bruce D Ratcliff'='RATCLIFB';'Patrick Lachica Encinas'='LACHICAP';'Joan M Hernandez Lopez'='HERNANDJ';'Guadalupe Ochoa Felix'='OCHOAFEG';'Clarence Broadbrooks'='BROADBRC'};foreach($x in $examples.GetEnumerator()){Assert ((Convert-DriverCode $x.Key)-eq$x.Value) "identity code $($x.Key)"}
  $xlsx=Join-Path $data 'Missing BOL.xlsx';$xh=@('Order #','TMEX Order #','Empty Call Date','Origin City St','Destination City St','Rev Type','Last Dispatch Driver cd','Last Dispatch Driver nm','Loaded Miles');$xv=@('ORD-X','TMEX-X','46161','Dallas TX','Tulsa OK','REG','D900','Bruce D Ratcliff','1370');New-TestXlsx $xlsx $xh $xv;$xc=Get-WaaCanonicalReportText $xlsx bol;Assert ($xc.Contains("Last Dispatch Driver cd")-and$xc.Contains('Bruce D Ratcliff')-and$xc.Contains('Dallas TX')) 'native XLSX/OpenXML Missing BOL extraction';Assert ($xc-notmatch "`t46161`t") 'Excel serial date normalized during XLSX intake'
  $dl=Join-Path $data 'Downloads';[IO.Directory]::CreateDirectory($dl)|Out-Null;$older=Join-Path $dl 'Rolling 7 Day.csv';$newer=Join-Path $dl 'Rolling 7 Day (1).csv';Set-Content $older 'old';Start-Sleep -Milliseconds 20;Set-Content $newer 'new';(Get-Item $older).LastWriteTimeUtc=(Get-Date).ToUniversalTime().AddMinutes(-10);Assert ((Get-WaaNewestDownload $dl idle).Name-eq'Rolling 7 Day (1).csv') 'Downloads intake chooses newest matching report only'
  $pta=@'
| Truck | Division | Driver Code | PTA | Operational Status | Planning Status | Operational Note | Driver Type | Location | N1 | N2 |
|---|---|---|---|---|---|---|---|---|---|---|
| 101 | D1 | CARMONAO | 08/08/2026 23:57 | Ready | Preplan | Call driver | Solo | Dallas | 3 | 9 |
| 202 | A2 |  | 12/31/26 23:59 | Clean\_QA | Unknown |  | Unknown | Yard | 8 | 1 |
'@
  $pre=Get-ImportPreview $pta 'pta.txt' auto;Assert ($pre.type-eq'pta'-and$pre.valid_rows-eq2) 'PTA Markdown parse and separator handling';$imp=Import-WaaData $pta 'pta.txt' auto;Assert ($imp.rows-eq2) 'PTA transactional import';$cur=@(Get-CurrentDrivers);Assert ($cur.Count-eq1-and$cur[0].pta_code-eq'CARMONAO') 'canonical driver and truck observation';$sent=Invoke-Sql "SELECT actionable,source_numeric_1,source_numeric_2 FROM pta_observations WHERE truck='202';" -Json;Assert ($sent[0].actionable-eq0-and$sent[0].source_numeric_1-eq'8') 'sentinel non-actionable and unknown numerics preserved';$pin=Invoke-Sql "SELECT count(*) c FROM pta_observations WHERE actionable=1 AND substr(pta_at,12,5)='23:57';" -Json;Assert ($pin[0].c-eq1) 'legitimate 23:57 retained actionable'
  $dupe=$false;try{Import-WaaData $pta 'again.txt' auto|Out-Null}catch{$dupe=$_.Exception.Message-like'Duplicate*'};Assert $dupe 'SHA-256 duplicate import blocked'
  $did=[int]$cur[0].id;Invoke-Sql "INSERT INTO idle_periods(driver_id,truck,period_start,period_end,engine_hours,idle_hours) VALUES($did,'101','2026-07-13','2026-07-19',20,2),($did,'101','2026-07-20','2026-07-26',40,7),($did,'101','2026-07-27','2026-08-02',10,8),($did,'101','2026-08-03','2026-08-09',30,3);" -AllowWrite|Out-Null;$dash=Get-Dashboard;$row=@($dash.drivers|Where-Object{$_.id-eq$did})[0];Assert ([double]$row.p7-eq10) 'latest idle percentage derived';Assert ([math]::Abs([double]$row.p28-20)-lt.01-and$row.coverage28-eq'Complete') '28-day percentage weighted, not averaged';Invoke-Sql "INSERT INTO drivers(full_name,pta_code) VALUES('Zero Driver','ZERODRIV');INSERT INTO idle_periods(driver_id,truck,period_start,period_end,engine_hours,idle_hours) VALUES(last_insert_rowid(),'0','2026-08-03','2026-08-09',0,0);" -AllowWrite|Out-Null;$zero=@((Get-Dashboard).drivers|Where-Object{$_.pta_code-eq'ZERODRIV'})[0];Assert ($null-eq$zero.p7-and$zero.coverage28-eq'Partial Data') 'zero engine hours is No Data and incomplete coverage is labeled'
  $card=Get-DriverCard $did;Save-DriverAction $did @{action='pta';value='08/10/2026 10:30'}|Out-Null;Assert ((Invoke-Sql "SELECT count(*) c FROM pta_observations WHERE driver_id=$did;" -Json)[0].c-eq2) 'manual PTA appends observation';Save-DriverAction $did @{action='note';text='Called driver'}|Out-Null;Save-DriverAction $did @{action='reminder';text='Check back';due_at='08/10/2026 12:00'}|Out-Null;Save-DriverAction $did @{action='timer';label='Thirty minutes';target_at='08/10/2026 11:00'}|Out-Null;$card=Get-DriverCard $did;Assert ($card.notes.Count-eq1-and$card.reminders.Count-eq1-and$card.timers.Count-eq1) 'notes reminders and timers persist'
  $one=Get-CurrentDriver $did;Assert ($one.id-eq$did-and$one.full_name-eq$cur[0].full_name) 'single-driver query returns canonical current state'
  $organizer=Get-Organizer;Assert ($organizer.items.Count-ge2-and@($organizer.items|Where-Object{$_.driver_id-eq$did}).Count-ge2) 'organizer keeps notes and reminders driver-specific'
  $dayStart=(Get-Date).ToUniversalTime().Date.ToString('yyyy-MM-dd HH:mm:ss');$dayEnd=(Get-Date).ToUniversalTime().Date.AddDays(1).ToString('yyyy-MM-dd HH:mm:ss');$activity=@(Get-DailyActivity $dayStart $dayEnd);Assert (@($activity|Where-Object{$_.driver_id-eq$did-and$_.action-eq'note'}).Count-ge1) 'daily review returns audited driver activity'
  Assert ((Invoke-Sql "SELECT count(*) c FROM sqlite_master WHERE type='index' AND name IN('idx_truck_driver_time','idx_notes_driver_created','idx_audit_time');" -Json)[0].c-eq3) 'driver and daily-review query indexes created'
  Save-DriverAction $did @{action='include_transition';value=$true}|Out-Null;Save-DriverAction $did @{action='transition_note';value='Follow up'}|Out-Null;$tr=Get-Transition -Regenerate;Assert ($tr.body.StartsWith("No Open ACE/ACI's")-and$tr.body.Contains('101 -')) 'transition exact header and truck-ordered item';Save-Transition 'Manual text'|Out-Null;Assert ((Get-Transition).body-eq'Manual text') 'manual transition persists'
  $headers=@('Order','Empty Call Date','Origin','Destination')+@(5..27|ForEach-Object{"Field $_"})+@('Last Dispatch Driver cd','Last Dispatch Driver nm');$values=@('ORD-1','08/01/2026','Dallas','Tulsa')+@(5..27|ForEach-Object{"v$_"})+@('D100','Driver Example');$bol=($headers-join"`t")+"`r`n"+($values-join"`t");$bp=Get-ImportPreview $bol 'Order Details Missing BOL.csv' auto;Assert ($bp.type-eq'bol'-and$bp.valid_rows-eq1) 'UTF-16 content-shaped 29-column BOL parser';Import-WaaData $bol 'Order Details Missing BOL.csv' auto|Out-Null;Assert ((Invoke-Sql "SELECT count(*) c FROM missing_bols WHERE order_number='ORD-1';" -Json)[0].c-eq1) 'Missing BOL stored by driver evidence'
  $idleHeader=@('Group by  (copy)','Unit Code','Week Start Date','Rolling 7 Day Start Date','[Rolling 7 Day Engine Time]/60','[Rolling 7 Day Idle Time]/60','Measure Names')-join',';$idleRow=@('D200 Example Driver','777','08/09/2026','08/03/2026','50','5','Idle %')-join',';$idleRaw=$idleHeader+"`r`n"+$idleRow;Assert ((Get-ImportPreview $idleRaw 'rolling.csv' auto).type-eq'idle') 'rolling idle content detection';Import-WaaData $idleRaw 'rolling.csv' auto|Out-Null;Assert ((Invoke-Sql "SELECT round(idle_hours*100.0/engine_hours,1) p FROM idle_periods WHERE truck='777';" -Json)[0].p-eq10) 'rolling idle parser stores base hours'
  $before=(Invoke-Sql 'SELECT count(*) c FROM import_batches;' -Json)[0].c;$bad=$false;try{Import-WaaData "bad`tidle`nrow" 'bad.tsv' idle|Out-Null}catch{$bad=$true};$after=(Invoke-Sql 'SELECT count(*) c FROM import_batches;' -Json)[0].c;Assert ($bad-or$before-eq$after) 'invalid import does not add operational rows'
  $b=Backup-Waa 'test';Assert (Test-Path $b.path) 'SQLite-safe backup created';Invoke-Sql "INSERT INTO settings(key,value) VALUES('persistence','yes');" -AllowWrite|Out-Null;Initialize-Waa $root $data|Out-Null;Assert ((Invoke-Sql "SELECT value FROM settings WHERE key='persistence';").Trim()-eq'yes') 'clean restart and persistence';Assert ((Get-DataQuality).backups.Count-ge1) 'automatic backup visible'
  $traversal=[IO.Path]::GetFullPath((Join-Path (Join-Path $root 'web') '../AGENTS.md'));Assert (!$traversal.StartsWith([IO.Path]::GetFullPath((Join-Path $root 'web'))+[IO.Path]::DirectorySeparatorChar)) 'path traversal canonicalization rejects outside file';$serverSource=Get-Content (Join-Path $root 'src/Server.ps1') -Raw;Assert ($serverSource.Contains('[Net.IPAddress]::Loopback')) 'server binds loopback only';Assert ($serverSource.Contains('26214400')-and$serverSource.Contains('StaticCache')-and$serverSource.Contains('ReadTimeout')) 'HTTP body limits, timeouts, and static cache enabled';$webIndex=Get-Content (Join-Path $root 'web/index.html') -Raw;Assert ($webIndex-notmatch'https?://') 'web client has no Internet dependency';Assert ($webIndex.Contains('#organizer')-and$webIndex.Contains('#activity')) 'driver organizer and daily-review tabs are integrated navigation'
  Write-Host "`nALL $script:Passed ASSERTIONS PASSED" -ForegroundColor Cyan
}finally{if(Test-Path $data){Remove-Item $data -Recurse -Force};Remove-Item Env:WAA_SQLITE_TEST -ErrorAction SilentlyContinue}
