<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <AssemblyName>WAA</AssemblyName>
    <RootNamespace>Waa.App</RootNamespace>
    <Version>0.4.1</Version>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <PublishSingleFile>false</PublishSingleFile>
    <PublishTrimmed>false</PublishTrimmed>
    <PublishReadyToRun>false</PublishReadyToRun>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Waa.Core\Waa.Core.csproj" />
    <PackageReference Include="Microsoft.Data.Sqlite" Version="8.0.30" />
  </ItemGroup>
</Project>
